enableGlobalCache: false
globalFolder: ".yarn/global"
nodeLinker: node-modules


packageExtensions: #this is supposed to fix googleMapsAPI dependencies, no clue lol
  "@vis.gl/react-google-maps@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
